import Head from "next/head";
import { useEffect } from "react";
import { useRouter } from "next/router";
// import { Inter } from "next/font/google";

// const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const router = useRouter();
  useEffect(() => {
    router.push("/countries").then();
  });
  return (
    <>
      <Head>
        <title>DabbleLab Talent Accelerator | Assignment</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>Home page</main>
    </>
  );
}
